name: Release Build

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore audiosynthSOL/audiosynth/audiosynth.csproj

    - name: Build
      run: dotnet build audiosynthSOL/audiosynth/audiosynth.csproj --configuration Release

    - name: Publish
      run: dotnet publish audiosynthSOL/audiosynth/audiosynth.csproj --configuration Release --output ./publish

    - name: Create ZIP
      run: |
        cd publish
        Compress-Archive -Path * -DestinationPath ../audiosynth.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload ZIP to Release
      uses: softprops/action-gh-release@v1
      with:
        files: audiosynth.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
